# Generated by Django 3.2 on 2022-01-31 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('reservations', '0002_reservation_res_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='profiles.userprofile'),
        ),
    ]
