# Generated by Django 3.2 on 2022-02-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(max_length=10)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
    ]
