# Generated by Django 3.2 on 2022-01-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=4)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
