# Generated by Django 3.2 on 2022-01-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycharges',
            options={'verbose_name_plural': 'Delivery_Charges'},
        ),
    ]
