# Generated by Django 3.2 on 2022-01-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_alter_deliverycharges_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycharges',
            options={'verbose_name_plural': 'DeliveryCharges'},
        ),
    ]
