# Generated by Django 3.2 on 2022-01-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='has_options',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
